### ISSUE TITLE
Null party signup during keygen (demo)

### ISSUE THREAD

**Issue by tmpfs** [LavaMoat/tss-snap#47]
Just came across this running the test suite using `test.sh`:

```
console.info:  client1 transition 0 to KEYGEN_ROUND_1
console.error:  client3 panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected struct PartySignup", line: 1, column: 4)', src/gg2020/keygen.rs:51:50

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (http://localhost:8080/wasm_pkg_ecdsa_wasm_js.index.js:350:19)
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[831]:0xb9e3f
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[233]:0x89369
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[612]:0xb4bae
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[640]:0xb546e
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[481]:0xaba77
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[212]:0x84a36
    at Object.keygenInit (http://localhost:8080/wasm_pkg_ecdsa_wasm_js.index.js:183:10)
    at callback (http://localhost:8080/vendors-node_modules_comlink_dist_esm_comlink_mjs.index.js:115:48)


console.info:  client2 transition 0 to KEYGEN_ROUND_1
unhandled error: client3 unreachable
```

**Comment by tmpfs** [comment]
We can see here that `client3` appears to be setting the `partySignup` for the keygen session state *after* calling `keygenInit`:

```
console.info:  client1 Set keygen session {phase: keygen, uuid: b2edb51f-9bd2-41e6-96ef-201b8aa6ccb8}
console.info:  client1 Set keygen session {phase: keygen, uuid: b2edb51f-9bd2-41e6-96ef-201b8aa6ccb8, partySignup: Object}
console.info:  client2 Set keygen session {phase: keygen, uuid: b2edb51f-9bd2-41e6-96ef-201b8aa6ccb8, partySignup: Object}
console.error:  client3 panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected struct PartySignup", line: 1, column: 4)', src
  ✘  tests/keygen-sign.spec.mjs:23:1 › create key shares and sign message (30s)

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (http://localhost:8080/wasm_pkg_ecdsa_wasm_js.index.js:350:19)
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[831]:0xb9e3f
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[233]:0x89369
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[612]:0xb4bae
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[640]:0xb546e
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[481]:0xaba77
    at http://localhost:8080/6f05be4d15933ff7c6d2.wasm:wasm-function[212]:0x84a36
    at Object.keygenInit (http://localhost:8080/wasm_pkg_ecdsa_wasm_js.index.js:183:10)
    at callback (http://localhost:8080/vendors-node_modules_comlink_dist_esm_comlink_mjs.index.js:115:48)


console.info:  client1 transition 0 to KEYGEN_ROUND_1
console.info:  client3 Set keygen session {phase: keygen, uuid: b2edb51f-9bd2-41e6-96ef-201b8aa6ccb8, partySignup: Object}
console.info:  client2 transition 0 to KEYGEN_ROUND_1
unhandled error: client3 unreachable
```

**Comment by tmpfs** [comment]
This appears to be a bug with the server emitting that event multiple times:

```
Sending threshold notify event sessionSignup for Keygen
Sending threshold notify event sessionSignup for Keygen
Sending threshold notify event sessionSignup for Sign
```

**Comment by tmpfs** [comment]
This has been worked around by polling in `waitForPartySignup`.

Still need to find the root cause of the problem.

**Comment by tmpfs** [comment]
Going to close this as the polling is working and is good enough for now.
